services:
  backend:
    build: ./backend
    ports:
      - "9000:9000"

  frontend:
    build: ./frontend
    environment:
      BACKEND_DNS: backend
    ports:
      - "8080:8080"
    depends_on:
      - backend
