apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ghcr.io/christianbendix/simple-fortune-cookie-project/backend:latest
          ports:
            - containerPort: 9000
          env:
            - name: REDIS_DNS
              valueFrom:
                configMapKeyRef:
                  name: fortune-config
                  key: REDIS_DNS