apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  labels:
    app: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      volumes:
        - name: database-pvc
          persistentVolumeClaim:
            claimName: database-pvc
      containers:
        - name: database
          image: redis:8.10.0
          ports:
            - containerPort: 6379
          env:
            - name: REDIS_ARGS
              valueFrom:
                configMapKeyRef:
                  name: fortune-config
                  key: REDIS_ARGS
          volumeMounts:
            - name: database-pvc
              mountPath: /data